wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    framework: xgboost
    huggingface_version: 4.37.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.19
    start_time: 1717408914
    t:
      1:
      - 1
      - 5
      - 6
      - 11
      - 49
      3:
      - 13
      - 16
      4: 3.8.19
      5: 0.12.11
      6: 4.37.2
      8:
      - 3
      - 5
config:
  desc: null
  value: conf/linear_regression.yaml
inherit:
  desc: null
  value:
  - C:\Users\bowen\Documents\GitHub Desktop\weeklong-mini-project---in-context-learning\wip\conf\base.yaml
model:
  desc: null
  value:
    family: gpt2
    n_dims: 20
    n_embd: 256
    n_head: 8
    n_layer: 12
    n_positions: 101
out_dir:
  desc: null
  value: ../models/linear_regression\e0284f8b-f3a0-40dd-b16f-6fa0ddf58475
test_run:
  desc: null
  value: false
training:
  desc: null
  value:
    batch_size: 64
    curriculum:
      dims:
        end: 20
        inc: 1
        interval: 2000
        start: 5
      points:
        end: 41
        inc: 2
        interval: 2000
        start: 11
    data: gaussian
    keep_every_steps: 100000
    learning_rate: 0.0001
    num_tasks: null
    num_training_examples: null
    resume_id: null
    save_every_steps: 1000
    task: linear_regression
    task_kwargs: {}
    train_steps: 500001
wandb:
  desc: null
  value:
    entity: ucla-bowenzheng
    log_every_steps: 1000
    name: linear_regression_standard
    notes: ''
    project: in-context-training
