config: conf/linear_regression-fixedcov_N70.yaml
inherit:
- C:\Users\bowen\Documents\GitHub Desktop\weeklong-mini-project---in-context-learning\fixedcov_N70\conf\base.yaml
model:
  family: gpt2
  n_dims: 20
  n_embd: 256
  n_head: 8
  n_layer: 12
  n_positions: 101
out_dir: ../models/linear_regression\f7bd747d-a5a1-4a0d-91d7-08d9e1ee8a8c
test_run: false
training:
  batch_size: 64
  curriculum:
    dims:
      end: 20
      inc: 1
      interval: 2000
      start: 5
    points:
      end: 71
      inc: 2
      interval: 2000
      start: 11
  data: gaussian
  keep_every_steps: 100000
  learning_rate: 0.0001
  num_tasks: null
  num_training_examples: null
  resume_id: null
  save_every_steps: 1000
  task: linear_regression
  task_kwargs: {}
  train_steps: 50001
wandb:
  entity: ucla-bowenzheng
  log_every_steps: 1000
  name: linear_regression_fixedcov_N70_test2
  notes: ''
  project: in-context-training
